#!/usr/bin/env python
#-*- coding:utf-8 -*-

"""
基于python2.7
"""

"""
1.抓取MM姓名，头像，年龄
2.资料简介和写真照片
3.写真照片按照文件夹保存到本地
"""

#不作处理直接抓取信息
import urllib
import urllib2
import re

#定义类，执行爬取工作
class Spider:
    #初始化基础页面
    def __init__(self):
        self.siteURL = "http:mm.taobao.com/json/request_top_list.htm"
    
    #定位到具体页面，并输出网址
    def getPage(self, pageIndex):
        #确定爬取的页面代码
        url = self.siteURL + "?page=" + str(pageIndex)
        #输出网址
        print (url)
        
        #构建request向url发送请求
        request = urllib2.Request(url)
        #使用urlopen获取url页面信息
        response = urllib2.urlopen(request)
        #将页面信息以‘gbk’格式编码后返回
        return response.read().decode('gbk')
    
    #定义函数，爬取内容
    def getContents(self, pageIndex):
        #调用getPage()函数，获取Index对应页面编码
        page = self.getPage(pageIndex)
        #设置正则表达式，筛选页面信息
        pattern = re.compile('<div class="list-item".*?pic-word.*?<a href="(.*?)".*?<img src="(.*?)"'
                         +'.*?<a class="lady-name.*?>(.*?)</a>.*?<strong>(.*?).*?</strong>.*?<span>(.*?)</span>')
        items = re.findall(pattern, page)
        for item in items:
            print (item[0].strip(), item[1].strip(), item[2].strip(), item[3].strip(), item[4].strip())
     
        
 spider = Spider()
 spider.getContents(1)
        
        
