#!/usr//bin/env python
#-*- coding:utf-8 -*-

import urllib
import urllib2
import re

class QSBK:

    def __init__(self):
        self.pageIndex = 1
        self.user_agent = "Mozilla 4.0(compatible; MSIE 5.5; Windows NT)"
        self.headers = {"User-Agent": self.user_agent}
        self.stories = []
        self.enable = False
        
    def getPage(self, pageIndex):
        try:
            url = "http://www.qiushibaike.com/hot/page/" + str(pageIndex)
            request = urllib2.Request(url, headers = self.headers)
            response = urllib2.urlopen(request)
            pageCode = response.read().decode("utf-8")
            return pageCode
            
        except urllib2.URLError, e:
            if hasattr(e, "reason"):
                print (u"连接糗百失败，失败原因：", e.reason)
                return None
                
    def getPageItems(self, pageIndex):
        pageCode = self.getPage(pageIndex)
        if not pageCode:
            print ("页面加载失败.....")
            return None
            
        pattern = re.compile('<div.*?author">.*?<a.*?<img.*?>(.*?)</a>.*?<div.*?'+
                         'content">(.*?)<!--(.*?)-->.*?</div>(.*?)<div class="stats.*?class="number">(.*?)</i>', re.S)
        items = re.findall(pattern, pageCode)
        pageStories = []
        for item in items:
            haveImg = re.search("img", item[3])
            if not haveImg:
                replaceBR = re.compile("</br>"
                text = re.sub(replaceBR, "\n", item[1])
                pageStories.append([item[0].strip(), text.strip(), item[2].strip(), item[4].strip()])
        return pageStories
        
    def loadPage(self):
        if self.enable == True
                                       
                                       
                                       
                             
                                       
                   
                                       
                                    
        
