#!/usr/bin/env python 
#-*- coding:utf-8 -*-

"""
对获取到的信息做处理
"""
import re

#定义工具类
class Tool:
    
    #去除img标签和7个空格
    removeImg = re.compile("<img.*?>| {7}|&nbsp;")
    #去除超链接标签
    removeAddr = re.compile("<a.*?>|</a>")
    #将换行标签同意更换为\n
    replaceLine = re.compile("<tr>|<div>|</div>|</p>")
    #将表格制表<td>替换为\t
    replaceTD = re.compile("<td>")
    #把段落开头换为\n加俩空格
    replacePara = re.compile("<p.*?>")
    #将换行符或者双换行符替换为\n
    replaceBR = re.compile("<br><br>|<br>")
    #去除其余标签
    removeExtraTag = re.compile("<.*?>")
    
    #对筛选后的代码处理
    def replace(self, x):
        x = re.sub(self.removeImg, "", x)
        x = re.sub(self.removeAddr, "", x)
        x = re.sub(self.removeExtraTag, "", x)
        x = re.sub(self.repalceLine, "\n", x)
        x = re.sub(self.repalceTD, "\t", x)
        x = re.sub(self.repalceBR, "\n", x)
        x = re.sub(self.replacePara, "  \n", x)
        #去除前后多余空格
        return x.strip()
